name: "kotlin-collection-manager"
services:
  file-service:
    image: openjdk:21-jdk-slim
    container_name: "file-service"
    restart: always
    ports:
      - "8082:8082"
    entrypoint: /bin/bash /home/startup.sh
    volumes:
      - ./docker:/home
    networks:
      backend-net:

networks:
  backend-net:
    driver: bridge