name: "kotlin-collection-manager"
services:
  invoker-service:
    image: openjdk:21-jdk-slim
    container_name: "invoker-service"
    restart: always
    ports:
      - "6000:6000"
      - "8080:8080"
    entrypoint: /bin/bash /home/startup.sh
    volumes:
      - ./docker:/home
    networks:
      backend-net:

networks:
  backend-net:
    driver: bridge